# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57528e50cc8b88e1f2dc37d534fc5cca0e65989448177ab3a6d22ae69e5e09309ea055125e352f9394fb5f22ba154e59167df149bdf5fef8060fef1a5fe9f414
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
test:
  secret_key_base: 5ca8aafd0ea894cc381292f3222a227ec2107e6b7e25fee4f268b8aa03c093fc131d820b4750421a7b967fee815816f1a4ba99141cd1a6c1ff6ffe5e5939494b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
